/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import implementacion.de.uso.pokemon.ColaCPU;
import implementacion.de.uso.pokemon.ColaGanador;
import implementacion.de.uso.pokemon.ColaJugador;
import implementacion.de.uso.pokemon.Ganador;
import implementacion.de.uso.pokemon.Pokemon;
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;

/**
 *
 * @author barah
 */
public class Batalla extends javax.swing.JFrame {

    private Pokemon pokemonJugador;
    private Pokemon pokemonCPU;
    private int turno;

    ColaJugador colaJugador = Pkv1.colaPk;
    ColaCPU colaCPU = Pkv1.colaSeleccionada;

    public Batalla() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        VidaCPU = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PokemonJug = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        VidaJugador = new javax.swing.JTextField();
        PokemonCPU = new javax.swing.JTextField();
        defensa = new javax.swing.JButton();
        cambiarPokemon = new javax.swing.JButton();
        DefensaEsp = new javax.swing.JButton();
        ataqueEsp = new javax.swing.JButton();
        ataque = new javax.swing.JButton();

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setText("Vida");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Pokemon Jugador");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Pokemon CPU ");

        VidaCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VidaCPUActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setText("Pokemon");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setText("Vida");

        PokemonJug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PokemonJugActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setText("Vida");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setText("Pokemon");

        VidaJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VidaJugadorActionPerformed(evt);
            }
        });

        PokemonCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PokemonCPUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VidaJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PokemonJug, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VidaCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PokemonCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VidaCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VidaJugador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PokemonJug, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PokemonCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        defensa.setText("Defensa");
        defensa.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        defensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defensaActionPerformed(evt);
            }
        });

        cambiarPokemon.setText("Cambiar pokemon");
        cambiarPokemon.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));

        DefensaEsp.setText("Defensa especial");
        DefensaEsp.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        DefensaEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefensaEspActionPerformed(evt);
            }
        });

        ataqueEsp.setText("Ataque especial");
        ataqueEsp.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        ataqueEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ataqueEspActionPerformed(evt);
            }
        });

        ataque.setText("Ataque");
        ataque.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        ataque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ataqueMouseClicked(evt);
            }
        });
        ataque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ataqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(ataque, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(ataqueEsp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DefensaEsp)
                .addGap(41, 41, 41)
                .addComponent(cambiarPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(defensa, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(defensa, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cambiarPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DefensaEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ataqueEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ataque, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ataqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ataqueActionPerformed

        try {
                    // Abre el archivo de sonido
                    File soundFile = new File("A-short-swing-of-a-sword-imbued-with-fire-magic.wav"); // Asegúrate de tener este archivo en la ubicación correcta
                    AudioInputStream audioIn = AudioSystem.getAudioInputStream(soundFile);

                    // Obtiene un clip de sonido
                    Clip clip = AudioSystem.getClip();

                    // Abre el clip de audio y comienza a reproducir el sonido
                    clip.open(audioIn);
                    clip.start();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
        if (colaJugador.ColaVacia() || colaCPU.ColaVacia()) {
            JOptionPane.showMessageDialog(null, "La batalla ha terminado.");
            if (colaJugador.ColaVacia()) {
                JOptionPane.showMessageDialog(null, "Lamento que hayas perdido, suerte para la proxima");
                Pkv1 pk = new Pkv1();
                pk.setVisible(true);

            } else if (colaCPU.ColaVacia()) {
                Ganador gan = new Ganador();
                Ganador nombreGan = new Ganador(1, JOptionPane.showInputDialog("Ingrese el nombre del ganador: "));
                ColaGanador colaGan = new ColaGanador();
                colaGan.encolar(nombreGan);
                colaGan.MostrarContenido();
                Principal p = new Principal();
                p.setVisible(true);

            }
            return;
        }
        if (pokemonJugador == null) {
            pokemonJugador = colaJugador.desencolar();
        }
        if (pokemonCPU == null) {
            pokemonCPU = colaCPU.desencolar();
        }

        int ataqueJugador = pokemonJugador.getAtaque();

        int defensaCPU = pokemonCPU.getDefensa();

        int danio = ataqueJugador - defensaCPU;

        if (danio < 0) {
            danio = 0;
        }

        pokemonCPU.setVida(pokemonCPU.getVida() - danio);

        VidaCPU.setText("VIda: " + pokemonCPU.getVida());
        VidaJugador.setText("Vida: " + pokemonJugador.getVida());
        PokemonJug.setText(pokemonJugador.getNombre());
        PokemonCPU.setText(pokemonCPU.getNombre());

        if (pokemonCPU.getVida() <= 0) {
            pokemonCPU = colaCPU.desencolar();
            if (pokemonCPU != null) {
                PokemonCPU.setText(pokemonCPU.getNombre());
            } else {
                PokemonCPU.setText("La CPU no tiene más Pokémon.");
            }
        }


    }//GEN-LAST:event_ataqueActionPerformed

    private void VidaCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VidaCPUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VidaCPUActionPerformed

    private void PokemonJugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PokemonJugActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PokemonJugActionPerformed

    private void VidaJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VidaJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VidaJugadorActionPerformed

    private void PokemonCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PokemonCPUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PokemonCPUActionPerformed

    private void defensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defensaActionPerformed
          try {
                    // Abre el archivo de sonido
                    File soundFile = new File("A-heavy-sword-unsheathed-from-its-sheats.wav"); // Asegúrate de tener este archivo en la ubicación correcta
                    AudioInputStream audioIn = AudioSystem.getAudioInputStream(soundFile);

                    // Obtiene un clip de sonido
                    Clip clip = AudioSystem.getClip();

                    // Abre el clip de audio y comienza a reproducir el sonido
                    clip.open(audioIn);
                    clip.start();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
        
        if (colaJugador.ColaVacia() || colaCPU.ColaVacia()) {
            JOptionPane.showMessageDialog(null, "La batalla ha terminado.");
            if (colaJugador.ColaVacia()) {
                JOptionPane.showMessageDialog(null, "Lamento que hayas perdido, suerte para la proxima");

            } else if (colaCPU.ColaVacia()) {
                Ganador gan = new Ganador();
                Ganador nombreGan = new Ganador(1, JOptionPane.showInputDialog("Ingrese el nombre del ganador: "));
                ColaGanador colaGan = new ColaGanador();
                colaGan.encolar(nombreGan);

            }
            return;
        }

        if (pokemonJugador == null) {
            pokemonJugador = colaJugador.desencolar();
        }
        if (pokemonCPU == null) {
            pokemonCPU = colaCPU.desencolar();
        }

        int defensaJug = pokemonJugador.getDefensa();


        int danio = pokemonCPU.getVida() - defensaJug;
        

        pokemonCPU.setVida(pokemonCPU.getVida()- danio);

        VidaCPU.setText("VIda: " + pokemonCPU.getVida());
        VidaJugador.setText("Vida: " + pokemonJugador.getVida());
        PokemonJug.setText(pokemonJugador.getNombre());
        PokemonCPU.setText(pokemonCPU.getNombre());

        if (pokemonJugador.getVida() <= 0) {
            pokemonJugador = colaJugador.desencolar();
            if (pokemonJugador != null) {
                PokemonJug.setText(pokemonJugador.getNombre());
            } else {
                PokemonJug.setText("El jugador no tiene más Pokémon.");
            }
        }


    }//GEN-LAST:event_defensaActionPerformed

    private void ataqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ataqueMouseClicked
        if (pokemonJugador == null) {
            pokemonJugador = colaJugador.desencolar();
        }
        if (pokemonCPU == null) {
            pokemonCPU = colaCPU.desencolar();
        }
        
        int defensaJug = pokemonJugador.getDefensa();
        int ataqueCPU = pokemonCPU.getAtaque();
        
        int danio = ataqueCPU - defensaJug;
        pokemonJugador.setVida(pokemonJugador.getVida()- danio);

        pokemonJugador.setVida(pokemonJugador.getVida());

        VidaJugador.setText("Vida: " + pokemonJugador.getVida());
        PokemonJug.setText(pokemonJugador.getNombre());

        if (pokemonJugador.getVida() <= 0) {
            pokemonJugador = colaJugador.desencolar();
            if (pokemonJugador != null) {
                PokemonJug.setText(pokemonJugador.getNombre());
            } else {
                PokemonJug.setText("El jugador no tiene más Pokémon.");
            }
        }

    }//GEN-LAST:event_ataqueMouseClicked

    private void ataqueEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ataqueEspActionPerformed
        try {
                    // Abre el archivo de sonido
                    File soundFile = new File("A-short-swing-of-a-sword-imbued-with-fire-magic.wav"); // Asegúrate de tener este archivo en la ubicación correcta
                    AudioInputStream audioIn = AudioSystem.getAudioInputStream(soundFile);

                    // Obtiene un clip de sonido
                    Clip clip = AudioSystem.getClip();

                    // Abre el clip de audio y comienza a reproducir el sonido
                    clip.open(audioIn);
                    clip.start();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
        if (colaJugador.ColaVacia() || colaCPU.ColaVacia()) {
            JOptionPane.showMessageDialog(null, "La batalla ha terminado.");
            if (colaJugador.ColaVacia()) {
                JOptionPane.showMessageDialog(null, "Lamento que hayas perdido, suerte para la proxima");
                Pkv1 pk = new Pkv1();
                pk.setVisible(true);

            } else if (colaCPU.ColaVacia()) {
                Ganador gan = new Ganador();
                Ganador nombreGan = new Ganador(1, JOptionPane.showInputDialog("Ingrese el nombre del ganador: "));
                ColaGanador colaGan = new ColaGanador();
                colaGan.encolar(nombreGan);
                colaGan.MostrarContenido();
                Principal p = new Principal();
                p.setVisible(true);

            }
            return;
        }
        if (pokemonJugador == null) {
            pokemonJugador = colaJugador.desencolar();
        }
        if (pokemonCPU == null) {
            pokemonCPU = colaCPU.desencolar();
        }

        int ataqueJugador = pokemonJugador.getAtaqueEspecial();

        int defensaCPU = pokemonCPU.getDefensa();

        int danio = ataqueJugador - defensaCPU;

        if (danio < 0) {
            danio = 0;
        }

        pokemonCPU.setVida(pokemonCPU.getVida() - danio);

        VidaCPU.setText("VIda: " + pokemonCPU.getVida());
        VidaJugador.setText("Vida: " + pokemonJugador.getVida());
        PokemonJug.setText(pokemonJugador.getNombre());
        PokemonCPU.setText(pokemonCPU.getNombre());

        if (pokemonCPU.getVida() <= 0) {
            pokemonCPU = colaCPU.desencolar();
            if (pokemonCPU != null) {
                PokemonCPU.setText(pokemonCPU.getNombre());
            } else {
                PokemonCPU.setText("La CPU no tiene más Pokémon.");
            }
        }
    }//GEN-LAST:event_ataqueEspActionPerformed

    private void DefensaEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefensaEspActionPerformed
        try {
                    // Abre el archivo de sonido
                    File soundFile = new File("A-heavy-sword-unsheathed-from-its-sheats.wav"); // Asegúrate de tener este archivo en la ubicación correcta
                    AudioInputStream audioIn = AudioSystem.getAudioInputStream(soundFile);

                    // Obtiene un clip de sonido
                    Clip clip = AudioSystem.getClip();

                    // Abre el clip de audio y comienza a reproducir el sonido
                    clip.open(audioIn);
                    clip.start();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
        
        if (colaJugador.ColaVacia() || colaCPU.ColaVacia()) {
            JOptionPane.showMessageDialog(null, "La batalla ha terminado.");
            if (colaJugador.ColaVacia()) {
                JOptionPane.showMessageDialog(null, "Lamento que hayas perdido, suerte para la proxima");

            } else if (colaCPU.ColaVacia()) {
                Ganador gan = new Ganador();
                Ganador nombreGan = new Ganador(1, JOptionPane.showInputDialog("Ingrese el nombre del ganador: "));
                ColaGanador colaGan = new ColaGanador();
                colaGan.encolar(nombreGan);

            }
            return;
        }

        if (pokemonJugador == null) {
            pokemonJugador = colaJugador.desencolar();
        }
        if (pokemonCPU == null) {
            pokemonCPU = colaCPU.desencolar();
        }

        int defensaJug = pokemonJugador.getDefensaEspecial();


        int danio = pokemonCPU.getVida() - defensaJug;
        

        pokemonCPU.setVida(pokemonCPU.getVida()- danio);

        VidaCPU.setText("VIda: " + pokemonCPU.getVida());
        VidaJugador.setText("Vida: " + pokemonJugador.getVida());
        PokemonJug.setText(pokemonJugador.getNombre());
        PokemonCPU.setText(pokemonCPU.getNombre());

        if (pokemonJugador.getVida() <= 0) {
            pokemonJugador = colaJugador.desencolar();
            if (pokemonJugador != null) {
                PokemonJug.setText(pokemonJugador.getNombre());
            } else {
                PokemonJug.setText("El jugador no tiene más Pokémon.");
            }
        }


    
    }//GEN-LAST:event_DefensaEspActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Batalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Batalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Batalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Batalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Batalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DefensaEsp;
    private javax.swing.JTextField PokemonCPU;
    private javax.swing.JTextField PokemonJug;
    private javax.swing.JTextField VidaCPU;
    private javax.swing.JTextField VidaJugador;
    private javax.swing.JButton ataque;
    private javax.swing.JButton ataqueEsp;
    private javax.swing.JButton cambiarPokemon;
    private javax.swing.JButton defensa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
